stages:
  - test
  - release
  - promote
  - deploy

image: python:3.12-bookworm
before_script:
  - pip install pdm>=2.23.1

variables:
  SERVERLESS_RELEASE_FILE: nextcloud_news_filter-$CI_COMMIT_TAG.zip

test:
  stage: test
  script:
    - pdm install -G:all
    - pdm test
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    # https://docs.gitlab.com/ee/ci/yaml/index.html#artifactsexpire_in
    expire_in: 2 week

    # https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

lint:
  stage: test
  script:
    - pdm install --dev
    - pdm lint

build-scaleway-zip:
  stage: release
  environment: production

  before_script:
    - apt-get update
    - apt-get install zip
    - pip install pdm
  script:
    - cd src
    - pdm export --prod -o requirements.txt
    - pip install -r requirements.txt --target ./package
    - zip -r ../$SERVERLESS_RELEASE_FILE nextcloud_news_filter/ package
  artifacts:
    paths:
      - ./$SERVERLESS_RELEASE_FILE
  only:
    - tags
    - main

publish-package-testing:
  stage: release
  environment: testing
  id_tokens:
    TESTPYPI_ID_TOKEN:
      aud: "testpypi"
  script:
    - pdm publish --repository testpypi
  dependencies:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - when: manual
      allow_failure: true

publish-package:
  stage: release
  environment: production
  id_tokens:
    PYPI_ID_TOKEN:
      aud: "pypi"
  script:
    - pdm publish
  dependencies: []
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]\.[0-9]((a|b|c|rc)\d+)?$/'

advertise:
  stage: promote
  before_script: []
  needs:
    - publish-package
  script:
    - pip install toot
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - mkdir -p ~/.config/toot/
    - mv .secure_files/config.json ~/.config/toot/config.json
    - toot post "I just released version $CI_COMMIT_TAG of nextcloud_news_filter. Read what is new`:` https://gitlab.com/lioman/nextcloud_news_filter/-/blob/$CI_COMMIT_TAG/CHANGELOG.md"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]\.[0-9]((a|b|c|rc)\d+)?$/'

deploy-nextcloud-news-filter:
  stage: deploy
  before_script: []
  image:
    name: scaleway/cli:2.32
    entrypoint: [""]
  environment: production
  script:
    - echo $SCW_DEFAULT_REGION
    - /scw function deploy name=nextcloud-news-filter namespace-id=$NAMESPACE_UUID runtime=python312 zip-file=./$SERVERLESS_RELEASE_FILE
    - /scw function function update timeout=300s sandbox=v2 $FUNCTION_UUID handler=nextcloud_news_filter.handler environment-variables.NEXTCLOUD_URL=$NEXTCLOUD_URL environment-variables.NEXTCLOUD_USER=$NEXTCLOUD_USER
  dependencies:
    - build-scaleway-zip
  only:
    - main

deploy-config:
  stage: deploy
  before_script: []
  image:
    name: scaleway/cli:2.32
    entrypoint: [""]
  environment: production
  script:
    - /scw function cron update $CRON_UUID args="`cat filter.json`" schedule="1/31 7-22 * * *"
  only:
    refs:
      - filter
    changes:
      - filter.json
      - .gitlab-ci.yml
  dependencies: []
